### ISSUE TITLE
[Calculator] The next day is choosen after presing the 1

### ISSUE THREAD

**Issue by AnastasiyaLazurenko** [AnastasiyaLazurenko/web.test#12]
**Steps to reproduce:**
1. Open the Calculator page
2. Open the Start date=>day dropdown
3. Click 1 on the keyboard a couple of times

**Actual result:** Days changes each time after clicking the button
**Expected result:** Th1 1 day is choosen

**Comment by varajan** [comment]
Cannot be fixed, as native HTML input behavior.
