### ISSUE TITLE
[Calculator] 31 is not available in the Date dropdown

### ISSUE THREAD

**Issue by AnastasiyaLazurenko** [AnastasiyaLazurenko/web.test#16]
**Steps to reproduce:**

1. Open the Calculator page
2. Open the Date dropdown

**Actual result:** The last day is 30
**Expected result:** The last day is 31

![image](https://github.com/user-attachments/assets/5c98558a-84d6-4570-85b9-5f09cc45f318)

**Comment by varajan** [comment]
Cannot reproduce. Maybe it was a side effect of #10
