### ISSUE TITLE
[Login page] The login occurs after insert the username in the uppercase

### ISSUE THREAD

**Issue by AnastasiyaLazurenko** [AnastasiyaLazurenko/web.test#2]
Steps to reproduce:
1. Open the login page
2. Use the following credentials: login - TEST, password - newyork1

Actual result: The login occurs after insert TEST login and valid password

Expected result: The following error message is expected: "Your username or password is incorrect"

**Comment by varajan** [comment]
Works as expected, login should be case-insensitive, but password - case-sensitive.
